"""
    DM.API Account

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dm_account_api
from dm_account_api.model.bad_request_error import BadRequestError


class TestBadRequestError(unittest.TestCase):
    """BadRequestError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBadRequestError(self):
        """Test BadRequestError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BadRequestError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
