"""
    DM.API Account

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import dm_account_api
from dm_account_api.api.login_api import LoginApi  # noqa: E501


class TestLoginApi(unittest.TestCase):
    """LoginApi unit test stubs"""

    def setUp(self):
        self.api = LoginApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_account_login_all_delete(self):
        """Test case for v1_account_login_all_delete

        Logout from every device  # noqa: E501
        """
        pass

    def test_v1_account_login_delete(self):
        """Test case for v1_account_login_delete

        Logout as current user  # noqa: E501
        """
        pass

    def test_v1_account_login_post(self):
        """Test case for v1_account_login_post

        Authenticate via credentials  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
