"""
    DM.API Account

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dm_account_api
from dm_account_api.model.user_details import UserDetails
globals()['UserDetails'] = UserDetails
from dm_account_api.model.user_details_envelope import UserDetailsEnvelope


class TestUserDetailsEnvelope(unittest.TestCase):
    """UserDetailsEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserDetailsEnvelope(self):
        """Test UserDetailsEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserDetailsEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
