"""
    DM.API Account

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dm_account_api
from dm_account_api.model.registration import Registration


class TestRegistration(unittest.TestCase):
    """Registration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRegistration(self):
        """Test Registration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Registration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
