"""
    DM.API Account

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import dm_account_api
from dm_account_api.api.account_api import AccountApi  # noqa: E501


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self):
        self.api = AccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_activate(self):
        """Test case for activate

        Activate registered user  # noqa: E501
        """
        pass

    def test_change_email(self):
        """Test case for change_email

        Change registered user email  # noqa: E501
        """
        pass

    def test_change_password(self):
        """Test case for change_password

        Change registered user password  # noqa: E501
        """
        pass

    def test_get_current(self):
        """Test case for get_current

        Get current user  # noqa: E501
        """
        pass

    def test_register(self):
        """Test case for register

        Register new user  # noqa: E501
        """
        pass

    def test_reset_password(self):
        """Test case for reset_password

        Reset registered user password  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
