"""
    DM.API Account

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dm_account_api
from dm_account_api.model.bb_parse_mode import BbParseMode
globals()['BbParseMode'] = BbParseMode
from dm_account_api.model.info_bb_text import InfoBbText


class TestInfoBbText(unittest.TestCase):
    """InfoBbText unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInfoBbText(self):
        """Test InfoBbText"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InfoBbText()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
