"""
    DM.API Account

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dm_account_api
from dm_account_api.model.color_schema import ColorSchema


class TestColorSchema(unittest.TestCase):
    """ColorSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testColorSchema(self):
        """Test ColorSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ColorSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
