"""
    DM.API Account

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dm_account_api
from dm_account_api.model.paging_settings import PagingSettings


class TestPagingSettings(unittest.TestCase):
    """PagingSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPagingSettings(self):
        """Test PagingSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PagingSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
