"""
    DM.API Account

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dm_account_api
from dm_account_api.model.change_password import ChangePassword


class TestChangePassword(unittest.TestCase):
    """ChangePassword unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChangePassword(self):
        """Test ChangePassword"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ChangePassword()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
