"""
    DM.API Account

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dm_account_api
from dm_account_api.model.login_credentials import LoginCredentials


class TestLoginCredentials(unittest.TestCase):
    """LoginCredentials unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoginCredentials(self):
        """Test LoginCredentials"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LoginCredentials()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
